name: watersystem
description: "Water system controller app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ESP32 Classic Bluetooth (SPP)
  flutter_bluetooth_serial: ^0.4.0

  # Permissions for Bluetooth and location
  permission_handler: ^12.0.1
  provider: ^6.1.1
  fl_chart: ^1.1.1
  shared_preferences: ^2.2.2
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  google_sign_in: ^6.2.1

  mongo_dart: ^0.10.5
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
